### ISSUE TITLE
From where do you come up with the ratio / weight list ?? 

### ISSUE THREAD

**Issue by ayanasser** [Ien001/CheXpert_challenge_2019#2]
Hi , 

I want to know From where do you come up with the ratio / weight list ?? 
    `weights = [0.2,0.9,0.7,0.4,0.4,0.3]`

**Comment by Ien001** [comment]
> Hi ,
> 
> I want to know From where do you come up with the ratio / weight list ??
> `weights = [0.2,0.9,0.7,0.4,0.4,0.3]`

Hi, 
I have tried different weights of the prediction of the models, and the weight in the code would allow my ensembled models to reach the highest performance in the local dataset.
As a result, I applied this weight to the testing environment.
Anyway, this is a trick.
